// Objective-C API for talking to github.com/kubenav/bind/request Go package.
//   gobind -lang=objc github.com/kubenav/bind/request
//
// File is generated by gobind. Do not edit.

#ifndef __Request_H__
#define __Request_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class RequestAPIError;

@interface RequestAPIError : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull kind;
@property (nonatomic) NSString* _Nonnull apiVersion;
@property (nonatomic) NSString* _Nonnull status;
@property (nonatomic) NSString* _Nonnull message;
@property (nonatomic) NSString* _Nonnull reason;
@property (nonatomic) long code;
@end

/**
 * Do runs the given HTTP request.
 */
FOUNDATION_EXPORT NSString* _Nonnull RequestDo(NSString* _Nullable method, NSString* _Nullable url, NSString* _Nullable body, NSString* _Nullable certificateAuthorityData, NSString* _Nullable clientCertificateData, NSString* _Nullable clientKeyData, NSString* _Nullable token, NSError* _Nullable* _Nullable error);

#endif
