
// Objective-C API for talking to the following Go packages
//
//	github.com/kubenav/bind/request
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Request_FRAMEWORK_H__
#define __Request_FRAMEWORK_H__

#include "Request.objc.h"
#include "Universe.objc.h"

#endif
